### ISSUE TITLE
BoilR cannot find Epic Games Store games in Steam Deck

### ISSUE THREAD

**Issue by Godslar** [PhilipK/BoilR#333]
My Deck both intalled Windows10 and Steam OS,and I using a share Disk to install Games

I installed Uplay and Epic by using Proton from Steam

When I open BoilR it can only recognize these app from Flatpak,the game I downloud from Uplay and Epic none of them is recognized.

I move the pointer on the Failed finding Games it shows :Error Message:Manifests not found

![Screenshot_20230209_143611](https://user-images.githubusercontent.com/74239235/217738900-f582d77a-aa39-4eaf-9860-19a188258d9a.png)

![Screenshot_20230209_143701](https://user-images.githubusercontent.com/74239235/217739007-f3500fab-ec17-4ada-a3d9-c9328d80a49d.png)

![Screenshot_20230209_143729](https://user-images.githubusercontent.com/74239235/217739034-e66b042d-ef81-4acf-bce2-d869f8e432f0.png)

 - Steam Deck
 - BoilR Version  v.1.7.2

**Comment by lihuixian001** [comment]
I have the same problem

“manifests no found”

**Comment by RufusJSquirrel** [comment]
I've had the same problem for a couple weeks - or at least a version of it.  I was originally able to import Epic games into Steam but when I installed a couple new ones, Boilr will not see them.  Curiously the ones Boilr added to Steam no longer show in the installed part of the Epic Games library and just these two new ones that won't import.

**Comment by tintin-92** [comment]
Appears to be related to closed issue #177. Still the same condition, hovering over the "Failed finding games" says "Manifests not found"

**Comment by GitE5H** [comment]
I'm having the same problem!!

**Comment by xiety** [comment]
I managed to solve this problem for my case.

For some reason I have my epic launcher inside `pfx/drive_c/Epic Games` path instead of `pfx/drive_c/Program Files (x86)/Epic Games` path, in one of my `home/deck/.local/share/Steam/steamapps/compatdata` folders.

So I moved it inside `Program Files (x86)`. And after that the games were found normally.

There may also be problems if you did not rename the installer in Steam, but added the Epic Launcher as a new application. In this case there will be two folders inside `compatdata`. And you need to move Epic Launcher from one folder to another.

I think you can also try to reinstall Epic Launcher to its default folder, following the instructions carefully.

**Comment by SpazShark** [comment]
I'm having a similar issue. If I have the games stored inside of the proton prefix folder ("home/deck/.local/share/Steam/steamapps/compatdata/randomnumber") then Boilr detects it. However, if I install the game to another location on my SSD (in my case "/home/deck/Games/Epic Games") then it Boilr won't pick this up.

Is anyone else experiencing this issue? I'm thinking I could fix this with a symlink but would rather avoid that hack.

**Comment by PhilipK** [comment]
This should be fixed in the newest version

**Comment by FoodFrisbee** [comment]
> This should be fixed in the newest version

hi, i'd like to report that im still having this issue with the lateest build
