### ISSUE TITLE
Every Boilr Run Creates Duplicates of Steam Shortcuts

### ISSUE THREAD

**Issue by kuynh** [PhilipK/BoilR#58]
Every time Bolir is ran, it creates duplicates of itch.io games that are already in the library.

**Comment by PhilipK** [comment]
This issue should be fixed in this release:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.16

(it is still building when i post this, so give it a couple minutes if the download is not ready yet)

If you can verify that it also works for you we can close this issue

**Comment by kuynh** [comment]
Still happens unfortunately
![image](https://user-images.githubusercontent.com/66544993/160260374-c3178eaf-9850-4c78-9e09-2ac8a0aa2024.png)

**Comment by PhilipK** [comment]
And this is even after you have deleted the doubles that it already created?

**Comment by kuynh** [comment]
Once I deleted the old ones it stopped duplicating. Thank you for fixing this issue.
